# SPDX-License-Identifier: Apache-2.0
---

- name: SAP Software Download - Download - Maintenance Plan - Get files
  community.sap_launchpad.software_center_download:
    suser_id: "{{ sap_software_download_suser_id }}"
    suser_password: "{{ sap_software_download_suser_password }}"
    download_link: "{{ item.DirectLink }}"
    download_filename: "{{ item.Filename }}"
    dest: "{{ sap_software_download_directory }}"
    validate_checksum: "{{ sap_software_download_validate_checksum | d(false) }}"
  # Loop condition acts as when conditional
  loop: "{{ __sap_software_download_fact_mp_files.download_basket | d([]) }}"
  loop_control:
    label: "{{ item.Filename }} : {{ __sap_software_download_files_plan_results.msg | d('') }}"
  register: __sap_software_download_files_plan_results
  environment: "{{ __venv_environment if sap_software_download_use_venv | d(true) else {} }}"
  vars:
    ansible_python_interpreter: "{{ __sap_software_download_fact_python_interpreter_path }}"
    __venv_environment:
      PATH: "{{ __sap_software_download_fact_venv_path }}"
      PYTHONPATH: "{{ __sap_software_download_fact_venv_pythonpath }}"
      VIRTUAL_ENV: "{{ __sap_software_download_register_temp_venv.path }}"
  ignore_errors: true  # Errors are ignored and validated afterwards


- name: SAP Software Download - Download - Maintenance Plan - Show failed results
  ansible.builtin.fail:
    msg: |
      FAIL: Maintenance Plan file(s) not found:  {{ __failed_items | map(attribute='item.Filename') | list | join(', ') }}
      Verify your Maintenance Plan in SAP Maintenance Planner before retrying.
  vars:
    __failed_items: "{{ __sap_software_download_files_plan_results.results
      | selectattr('failed', 'defined') | selectattr('failed', 'true') }}"
  when:
    - not sap_software_download_ignore_file_not_found | d(false)
    - __failed_items | length > 0
