# SPDX-License-Identifier: Apache-2.0
---

# Example of files loading order:
# 1. Suse.yml / RedHat.yml - Specific to OS family.
# 2. SLES_15.yml / RedHat_9.yml - Specific to distribution (SLES, SLES_SAP or RedHat) and major release.
# 3. SLES_15.6.yml / RedHat_9.2 - Specific to distribution (SLES, SLES_SAP or RedHat) and minor release.
# 4. SLES_SAP_15.yml - Specific to distribution SLES_SAP and major release.
# 5. SLES_SAP_15.6.yml - Specific to distribution SLES_SAP and minor release.
- name: SAP Software Download - Include OS specific variables
  ansible.builtin.include_vars: "{{ __vars_file }}"
  loop: "{{ __var_files }}"
  vars:
    __vars_file: "{{ role_path }}/vars/{{ item }}"
    __distribution_major: "{{ ansible_facts['distribution'] ~ '_' ~ ansible_facts['distribution_major_version'] }}"
    __distribution_minor: "{{ ansible_facts['distribution'] ~ '_' ~ ansible_facts['distribution_version'] }}"
    # Enables loading of shared vars between SLES and SLES_SAP
    __distribution_major_split: "{{ ansible_facts['distribution'].split('_')[0] ~ '_' ~ ansible_facts['distribution_major_version'] }}"
    __distribution_minor_split: "{{ ansible_facts['distribution'].split('_')[0] ~ '_' ~ ansible_facts['distribution_version'] }}"
    __var_files: >-
      {{
        [
          ansible_facts['os_family'] ~ '.yml',
          (ansible_facts['distribution'] ~ '.yml') if ansible_facts['distribution'] != ansible_facts['os_family'] else None,
          (__distribution_major_split ~ '.yml') if __distribution_major_split != __distribution_major else None,
          (__distribution_minor_split ~ '.yml') if __distribution_minor_split != __distribution_minor else None,
          __distribution_major ~ '.yml',
          __distribution_minor ~ '.yml'
        ] | select('defined') | select('string') | list
      }}
  when: __vars_file is file

- name: SAP Software Download - Include tasks to validate variables
  ansible.builtin.include_tasks:
    file: pre_steps/validate_variables.yml

- name: Block to cleanup Python venv in case of failure during variable validation
  block:

    - name: SAP Software Download - Include tasks to prepare environment
      ansible.builtin.include_tasks:
        file: pre_steps/prepare_environment.yml

    - name: SAP Software Download - Include tasks to validate user credentials
      ansible.builtin.include_tasks:
        file: pre_steps/validate_credentials.yml
      when: not sap_software_download_ignore_validate_credentials | d(false)

    - name: SAP Software Download - Include tasks to find files for Maintenance Plan
      ansible.builtin.include_tasks:
        file: pre_steps/get_plan_files.yml
      when:
        - sap_software_download_mp_transaction | length > 0

    # NOTE: We do not validate files generated by Maintenance Plan.
    - name: SAP Software Download - Include tasks to check related SAP Software combinations
      ansible.builtin.include_tasks:
        file: pre_steps/validate_relationships.yml
      when:
        - sap_software_download_files | length > 0
        - sap_software_download_validate_relationships


    - name: SAP Software Download - Include tasks to download Stack XML
      ansible.builtin.include_tasks:
        file: download_stack.yml
      when:
        - sap_software_download_mp_transaction | length > 0
        - sap_software_download_mp_stack_xml | d(true)

    - name: SAP Software Download - Include tasks to download files defined in the Maintenance Plan
      ansible.builtin.include_tasks:
        file: download_plan.yml
      when:
        - sap_software_download_mp_transaction | length > 0
        - __sap_software_download_fact_mp_files.download_basket is defined
          and __sap_software_download_fact_mp_files.download_basket | length > 0

    - name: SAP Software Download - Include tasks to download files in the variable 'sap_software_download_files'
      ansible.builtin.include_tasks:
        file: download_files.yml
      when: sap_software_download_files | length > 0

  always:
    - name: SAP Software Download - Include tasks for cleanup of Python environment
      ansible.builtin.include_tasks:
        file: post_steps/cleanup_python_environment.yml
