# SPDX-License-Identifier: Apache-2.0
---

# HANA 1: IMDB_CLIENT100_120_140-10009663.SAR
# - IMDB_CLIENT100 - HANA 2.0 identifier
#
# HANA 2: IMDB_CLIENT20_028_21-80002082.SAR (SAP HANA Client 2.28.21)
# - IMDB_CLIENT20 - HANA 2.0 identifier
